preferred_solution_number: 3
tool_mass: 3.44
pulley_bearing_position: [-0.6654834316385497, -0.0844570012960042, 0.2551901723057327, -1.484318068681165, 0.6191402790204206, -0.6254296057933952] # big pulley
initial_joint_states : [3.87083, -2.28049, -1.3507, -2.64271, 1.08987, 3.12731] # for gazebo
task_initial_position: [0.03, 0, -0.02, 0,-25,0] # in relative to bigger pulley bearing's frame.
pulley_radious: [0.03,0.015]

#force controller gain
f_x_kp : 0.00007
f_x_ki : 0
f_x_kd : 0

f_y_kp : 0
f_y_ki : 0
f_y_kd : 0

f_z_kp : 0
f_z_ki : 0
f_z_kd : 0

f_eaa_x_kp : 0
f_eaa_x_ki : 0
f_eaa_x_kd : 0

f_eaa_y_kp : 0
f_eaa_y_ki : 0
f_eaa_y_kd : 0

f_eaa_z_kp : 0
f_eaa_z_ki : 0
f_eaa_z_kd : 0

#position controller gain
p_x_kp : 0.8
p_x_ki : 0
p_x_kd : 0

p_y_kp : 0
p_y_ki : 0
p_y_kd : 0

p_z_kp : 0
p_z_ki : 0
p_z_kd : 0

p_eaa_x_kp : 0
p_eaa_x_ki : 0
p_eaa_x_kd : 0

p_eaa_y_kp : 0
p_eaa_y_ki : 0
p_eaa_y_kd : 0

p_eaa_z_kp : 0
p_eaa_z_ki : 0
p_eaa_z_kd : 0

master_pulley_0: 
  0: [0.035,0,-0.01,0,-25,0,2.5] # close to the pulley
  1: [-0.012,0.043,-0.006,0,-25,-30,7] # a desired belt point
  2: [0.035,-0.04,-0.006,-30,-25,0,2.5] # up motion
  3: [-0.032,-0.04,-0.006,0,-25,0,2.5] # finish1
  4: [-0.032,-0.04,-0.04,0,-25,0,2.5]  # finish1
  5: [0,-0.04,-0.04,0,-25,0,2.5]  # finish1

slave_0: # 
  0: [0.02,-0.02,-0.005,0,0,0,2.5] # close to the pulley
  1: [0.02,-0.02,-0.005,0,0,0,2.5] # keep the previous position

robust_force_value:
  0: [0,0,0]
  1: [0,0,0]
