preferred_solution_number: 3 #3,4
tool_mass: 3.44
part_position: [-0.662818, -0.083727, 0.249723, -1.484318068681165, 0.6191402790204206, -0.6254296057933952]   #pulley_big
robot_initial_pose:  [-0.677396, -0.126005, 0.249932, -1.55753, 0.279892, -0.284414] 
initial_joint_states : [3.86149, -2.3145, -1.2996, -2.66389, 1.07926, 3.1354] # for gazebo
pulley_radious: [0.0175,0.0275]

#force controller gain
f_x_kp : 0.00007
f_x_ki : 0
f_x_kd : 0

f_y_kp : 0
f_y_ki : 0
f_y_kd : 0

f_z_kp : 0
f_z_ki : 0
f_z_kd : 0

f_eaa_x_kp : 0
f_eaa_x_ki : 0
f_eaa_x_kd : 0

f_eaa_y_kp : 0
f_eaa_y_ki : 0
f_eaa_y_kd : 0

f_eaa_z_kp : 0
f_eaa_z_ki : 0
f_eaa_z_kd : 0

#position controller gain
p_x_kp : 0.8
p_x_ki : 0
p_x_kd : 0

p_y_kp : 0
p_y_ki : 0
p_y_kd : 0

p_z_kp : 0
p_z_ki : 0
p_z_kd : 0

p_eaa_x_kp : 0
p_eaa_x_ki : 0
p_eaa_x_kd : 0

p_eaa_y_kp : 0
p_eaa_y_ki : 0
p_eaa_y_kd : 0

p_eaa_z_kp : 0
p_eaa_z_ki : 0
p_eaa_z_kd : 0

#everyting is with respect to own pulley's frame 

master_pulley_big: 
  0: [0.033,0,-0.01,0,-25,0,2.5] # close to the pulley
  1: [-0.013,0.029,-0.004,0,-25,-15,3] # a desired belt point
  2: [0.033,-0.045,-0.012, -30,-25,0,1.5] # up motion
  3: [-0.01,-0.047,-0.012, -30,-25,0,1.5] # finish1
  4: [-0.01,-0.047,-0.04, 0,-25,0,1.5]  # finish1
  5: [0.07,-0.045,-0.05,0,-25,0,1.5]  # finish1

slave_pulley_big: # 
  0: [0.02,-0.02,-0.005,0,0,0,2.5] # close to the pulley
  1: [0.02,-0.02,-0.005,0,0,0,2.5] # keep the previous position

desired_force_value:
  0: [0,0,0]
  1: [0,0,0]
