preferred_solution_number: 3 #3
tool_mass: 1.70
part_position: [-0.745247, 0.0747897, 0.242603, -0.7313354979535918, -1.7622417854008892, 1.7568650899341813] #pulley_big
robot_initial_pose: [-0.619116, 0.0171242, 0.244798, -0.731335, -1.76224, 1.75687] #robot initial pose
initial_joint_states : [2.98038, -1.64919, -2.33318, -2.30609, -2.51614, -3.14578] # for gazebo
pulley_radious: [0.0175,0.0275]

#force controller gain
f_x_kp : 0.0008 #
f_x_ki : 0
f_x_kd : 0

f_y_kp : 0
f_y_ki : 0
f_y_kd : 0

f_z_kp : 0
f_z_ki : 0
f_z_kd : 0

f_eaa_x_kp : 0
f_eaa_x_ki : 0
f_eaa_x_kd : 0

f_eaa_y_kp : 0
f_eaa_y_ki : 0
f_eaa_y_kd : 0

f_eaa_z_kp : 0
f_eaa_z_ki : 0
f_eaa_z_kd : 0

#position controller gain
p_x_kp : 0.06 #0.17
p_x_ki : 0
p_x_kd : 0

p_y_kp : 0
p_y_ki : 0
p_y_kd : 0

p_z_kp : 0
p_z_ki : 0
p_z_kd : 0

p_eaa_x_kp : 0
p_eaa_x_ki : 0
p_eaa_x_kd : 0

p_eaa_y_kp : 0
p_eaa_y_ki : 0
p_eaa_y_kd : 0

p_eaa_z_kp : 0
p_eaa_z_ki : 0
p_eaa_z_kd : 0

#everyting is with respect to own pulley's frame 
master_pulley_small: # 
  0: [-0.04,0,-0.008,0,0,0,5] # close to the pulley
  1: [0,0.009,-0.005,0,0,-20,5] # a desired belt point
  2: [-0.04,-0.03,-0.01,20,0,0,3] # up motion
  3: [0.01,-0.032,-0.01,20,0,0,3]  # finish1
  4: [0.01,-0.032,-0.01,20,0,0,3] # finish1
  5: [-0.06,-0.032,-0.04,0,0,0,3] # finish1

slave_pulley_small: # 
  0: [-0.03,-0.02,-0.025,0,0,0,5] # close to the pulley
  1: [-0.03,-0.02,-0.025,0,0,0,5] # keep the previous position

desired_force_value:
  0: [7,1.3,1]
  1: [7,1.3,1]





